apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    
    http {
        log_format security_logs '$http_x_forwarded_for - $remote_user [$time_local] '
                                 '"$request" $status $body_bytes_sent '
                                 '"$http_user_agent"';
    
        access_log /var/log/nginx/access.log security_logs;
        
        # Trust Traffic Gen Headers
        set_real_ip_from 0.0.0.0/0; 
        real_ip_header X-Forwarded-For;
        real_ip_recursive on;
    
        server {
            listen 80;
            
            # Dynamic Blocklist from Shared Volume
            include /etc/nginx/conf.d/block.conf;
    
            location / {
                # Forward to DLP Service
                proxy_pass http://dlp:5000;
                
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $http_x_forwarded_for;
            }
        }
    }