# --- TARGET APP (Juice Shop) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: target-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: target-app
  template:
    metadata:
      labels:
        app: target-app
    spec:
      containers:
      - name: target-app
        image: bkimminich/juice-shop:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: target-app
spec:
  selector:
    app: target-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP

---
# --- DLP SERVICE ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dlp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dlp
  template:
    metadata:
      labels:
        app: dlp
    spec:
      containers:
      - name: dlp
        image: ullas474/autonet-dlp:latest
        ports:
        - containerPort: 5000
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        # --- REQUIRED FOR HPA SCALING ---
        resources:
          requests:
            cpu: "100m"  # 0.1 CPU Core reserved
          limits:
            cpu: "500m"  # 0.5 CPU Core max
        # -------------------------------
---
apiVersion: v1
kind: Service
metadata:
  name: dlp
spec:
  selector:
    app: dlp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP